(cl:defpackage deeporange14_msgs-msg
  (:use )
  (:export
   "<AUSTATUSMSG>"
   "AUSTATUSMSG"
   "<MISSIONSTATUS>"
   "MISSIONSTATUS"
   "<MOBILITYMSG>"
   "MOBILITYMSG"
   "<PIDCOMPONENTSMSG>"
   "PIDCOMPONENTSMSG"
   "<RAPTORSTATEMSG>"
   "RAPTORSTATEMSG"
   "<TORQUECMDSTAMPED>"
   "TORQUECMDSTAMPED"
  ))

