# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from deeporange14_msgs/PIDComponentsMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PIDComponentsMsg(genpy.Message):
  _md5sum = "cc85b3278733449a3886e64952b6b2bc"
  _type = "deeporange14_msgs/PIDComponentsMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 P_Vx
float64 I_Vx
float64 D_Vx
float64 P_Wz
float64 I_Wz
float64 D_Wz"""
  __slots__ = ['P_Vx','I_Vx','D_Vx','P_Wz','I_Wz','D_Wz']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       P_Vx,I_Vx,D_Vx,P_Wz,I_Wz,D_Wz

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PIDComponentsMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.P_Vx is None:
        self.P_Vx = 0.
      if self.I_Vx is None:
        self.I_Vx = 0.
      if self.D_Vx is None:
        self.D_Vx = 0.
      if self.P_Wz is None:
        self.P_Wz = 0.
      if self.I_Wz is None:
        self.I_Wz = 0.
      if self.D_Wz is None:
        self.D_Wz = 0.
    else:
      self.P_Vx = 0.
      self.I_Vx = 0.
      self.D_Vx = 0.
      self.P_Wz = 0.
      self.I_Wz = 0.
      self.D_Wz = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.P_Vx, _x.I_Vx, _x.D_Vx, _x.P_Wz, _x.I_Wz, _x.D_Wz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.P_Vx, _x.I_Vx, _x.D_Vx, _x.P_Wz, _x.I_Wz, _x.D_Wz,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.P_Vx, _x.I_Vx, _x.D_Vx, _x.P_Wz, _x.I_Wz, _x.D_Wz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.P_Vx, _x.I_Vx, _x.D_Vx, _x.P_Wz, _x.I_Wz, _x.D_Wz,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
